<a href="https://colab.research.google.com/github/Aadarsh1999794/Python-and-Machine-Learning/blob/main/Copy_of_PracticePS_session_Pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas-1

### Question:

You are given an employee dataset in a CSV file named 'employee_data.csv'. Your task is to analyze this data using Pandas, focusing on the following operations:

1. Load the data from 'employee_data.csv' into a DataFrame. Data is given:

**data = {
    'EmployeeID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Name': ['John Doe', 'Jane Smith', 'Mike Johnson', 'Emily Brown', 'David Lee', 'Sarah Wilson', 'Tom Davis', 'Lisa Chen', 'Ryan Taylor', 'Emma White'],
    'Department': ['IT', 'HR', 'Finance', 'Marketing', 'IT', 'HR', 'Finance', 'Marketing', 'IT', 'Finance'],
    'Salary': [75000, 65000, 80000, 70000, 78000, 67000, 82000, 71000, 76000, 81000],
    'YearsOfService': [5, 3, 7, 4, 6, 2, 8, 3, 5, 6]
}**

<br>

2. Display the first 3 rows and the last 2 rows of the DataFrame.
3. Show the shape of the DataFrame and list its column names.
4. Provide a concise summary of the DataFrame's content.
5. Rename the 'YearsOfService' column to 'Experience'.
6. Create a new column 'SalaryPerYear' by dividing 'Salary' by 'Experience'.
7. Display the number of unique departments and the count of employees in each department.
8. Set 'EmployeeID' as the index of the DataFrame.
9. Use loc to select employees from the IT department and iloc to select the first 5 rows and first 3 columns.
10. Drop the 'Salary' column.
11. Reset the index of the DataFrame.

In [1]:
import pandas as pd

data = {
    'EmployeeID': [1, 2, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Name': ['John Doe', 'Jane Smith', 'Jane Smith', 'Mike Johnson', 'Emily Brown', 'David Lee', 'Sarah Wilson', 'Tom Davis', 'Lisa Chen', 'Ryan Taylor', 'Emma White'],
    'Department': ['IT', 'HR','HR', 'Finance', 'Marketing', 'IT', 'HR', 'Finance', 'Marketing', 'IT', 'Finance'],
    'Salary': [75000, 65000, 62000, 80000, 70000, 78000, 67000, 82000, 71000, 76000, 81000],
    'YearsOfService': [5, 3, 3, 7, 4, 6, 2, 8, 3, 5, 6] # Rename this to Experience
}

df = pd.DataFrame(data)

# First 3 rows
print(df.head(3)) # Display the first n rows

# Last 3 rows
print(df.tail(3)) # Display the last n rows

# Show the shape of the DataFrame and list its column names.
print(df.shape)
print(df.columns)

# Provide a concise summary of the DataFrame's content.
print(df.info()) # Summary

# Rename the 'YearsOfService' column to 'Experience'.
df.rename(columns={"YearsOfService" : "Experience"}, inplace=True)

# Create a new column 'SalaryPerYear' by dividing 'Salary' by 'Experience'.
df['SalaryPerYear'] = df['Salary'] / df['Experience']

# Display the number of unique departments and the count of employees in each department.
print(df['Department'].nunique()) # Number of unique

print(df['Department'].value_counts()) # The number of times a department occurs or its frequency

# Set 'EmployeeID' as the index of the DataFrame.
df.set_index('EmployeeID', inplace=True)

# Use loc to select employees from the IT department and iloc to select the first 5 rows and first 3 columns.
print(df.loc[df['Department'] == 'IT'])

print(df.iloc[ : 5, : 3]) # df.iloc[rows, columns]

# Drop the 'Salary' column.
df.drop('Salary', axis=1, inplace=True)

# Reset the index of the DataFrame.
df.reset_index(inplace=True, drop=True)

print(df)

   EmployeeID        Name Department  Salary  YearsOfService
0           1    John Doe         IT   75000               5
1           2  Jane Smith         HR   65000               3
2           2  Jane Smith         HR   62000               3
    EmployeeID         Name Department  Salary  YearsOfService
8            8    Lisa Chen  Marketing   71000               3
9            9  Ryan Taylor         IT   76000               5
10          10   Emma White    Finance   81000               6
(11, 5)
Index(['EmployeeID', 'Name', 'Department', 'Salary', 'YearsOfService'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   EmployeeID      11 non-null     int64 
 1   Name            11 non-null     object
 2   Department      11 non-null     object
 3   Salary          11 non-null     int64 
 4   YearsOfService  11 non-null     int64

In [ ]:
#rom posixpath import expanduser
#print(df['Department'].nunique()) # Number of unique
#print(df['Department'].value_counts())
#df.reset_index(inplace=True,drop=True)
#print(df.columns)
#df.reset_index(inplace=True, drop=True)
#print(df.columns)
#df.set_index('Department',inplace=True)
#type(df['Experience'])
#df
#df['Experience'].value_counts()
#df.rename({'Experience':'Exp'}, axis=1)

# OR

#df.rename( ={'Experience' : 'Exp'})
#df.reset_index(inplace=True)   #Reset dataframe in pandas
#df
#df.index.values
#df.index.values
import numpy as np
#df.index=np.arange(1,df.shape[0]+1,dtype='float')
#sample=df.head()
#sample.index=['a','b','c','d','e']
#sample.reset_index(inplace=True)
#sample
#df.reset_index(inplace=True)
df.index=np.arange(1,df.shape[0]+1)
df.loc[2]

Name               Jane Smith
Department                 HR
Experience                  3
SalaryPerYear    21666.666667
Name: 2, dtype: object

In [ ]:
df.drop_duplicates(subset=['Name'], keep='last') # It will all the duplicates and keep the first row by default

index          Name Department  Experience  SalaryPerYear
1       0      John Doe         IT           5   15000.000000
3       2    Jane Smith         HR           3   20666.666667
4       3  Mike Johnson    Finance           7   11428.571429
5       4   Emily Brown  Marketing           4   17500.000000
6       5     David Lee         IT           6   13000.000000
7       6  Sarah Wilson         HR           2   33500.000000
8       7     Tom Davis    Finance           8   10250.000000
9       8     Lisa Chen  Marketing           3   23666.666667
10      9   Ryan Taylor         IT           5   15200.000000
11     10    Emma White    Finance           6   13500.000000

In [ ]:
# Unique() function works for series, nunique() works for both
#df.nunique() # Number of unique values in each column
#Department.nunique()
#df['Name'].nunique()
df['Experience'].nunique()
#df['Name'].value_counts()

7

In [ ]:
# Statistical Summary of the data
#print(df.describe())
#print(df.head(10))
#df.shape
#df.dtypes
#df.describe().T
#df.duplicated().sum()
#df.isnull().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Name           11 non-null     object 
 1   Department     11 non-null     object 
 2   Experience     11 non-null     int64  
 3   SalaryPerYear  11 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 480.0+ bytes


### Question:

You are a product manager for an electronics store. You've been given a data containing information about your products. Your task is to analyze this data and find the product with the highest total value in stock. To do this, you'll need to use various Pandas operations.

Follow these steps to solve the problem:

1. Load the data into dataframe.  

Sample dataset:  

**data = {
    'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05'],
    'Product_ID': ['A001', 'B002', 'C003', 'A001', 'B002'],
    'Product_Name': ['Laptop', 'Smartphone', 'Tablet', 'Laptop', 'Smartphone'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics'],
    'Price': [1200, 800, 500, 1200, 800],
    'Stock': [50, 100, 75, 45, 95]
}**

<br>

2. Display the first 3 rows of the dataset to familiarize yourself with its structure.
3. Check the basic information about the dataset, including column names and data types.
4. Rename the 'Stock' column to 'Quantity_in_Stock' for clarity.
5. Create a new column called 'Total_Value' by multiplying 'Price' and 'Quantity_in_Stock'.
6. Set the 'Product_ID' as the index of the DataFrame.
7. Using the 'loc' accessor, find the 'Total_Value' for the product with ID 'B002'.
8. Drop the 'Category' column as it's not needed for this analysis.
9. Reset the index to make 'Product_ID' a regular column again.
10. Use 'iloc' to display the 'Product_Name' and 'Total_Value' of the last product in the DataFrame.
11. Find the number of unique products in the dataset.
12. Identify the product with the highest 'Total_Value' and display its name.

In [ ]:
import pandas as pd

# Sample dataset
data = {
    'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05'],
    'Product_ID': ['A001', 'B002', 'C003', 'A001', 'B002'],
    'Product_Name': ['Laptop', 'Smartphone', 'Tablet', 'Laptop', 'Smartphone'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics'],
    'Price': [1200, 800, 500, 1200, 800],
    'Stock': [50, 100, 75, 45, 95]
}

# 1. Load the data
df = pd.DataFrame(data)

# 2. Display the first 3 rows of the dataset to familiarize yourself with its structure.
print(df.head(3))

# Rename the 'Stock' column to 'Quantity_in_Stock' for clarity.
df.rename(columns={'Stock' : 'Quantity_in_Stock'}, inplace=True)

# Create a new column called 'Total_Value' by multiplying 'Price' and 'Quantity_in_Stock'.
df['Total_Value'] = df['Price'] * df['Quantity_in_Stock']

# Set the 'Product_ID' as the index of the DataFrame.
df.set_index('Product_ID', inplace=True)

# Using the 'loc' accessor, find the 'Total_Value' for the product with ID 'B002'.
print(df.loc['B002', 'Total_Value'])

# Drop the 'Category' column as it's not needed for this analysis.
df.drop('Category', axis=1, inplace=True)

# Reset the index to make 'Product_ID' a regular column again.
df.reset_index(inplace=True)

# print(df.head())
# Use 'iloc' to display the 'Product_Name' and 'Total_Value' of the last product in the DataFrame
df.iloc[-1 : , [2,5]] # -1 last row, [2, 5] -> 3rd and 6th column

# Find the number of unique products in the dataset.
df['Product_ID'].nunique()


# Identify the product with the highest 'Total_Value' and display its name
highest_total_value = df['Total_Value'].max()

# All the rows where total value is equal to highest_total_value
df.loc[df['Total_Value'] == highest_total_value, ['Product_ID', 'Product_Name']]


# df['Total_Value'] == df['Total_Value'].max() -> total_value should be equal to the maximum possible values

         Date Product_ID Product_Name     Category  Price  Stock
0  2023-01-01       A001       Laptop  Electronics   1200     50
1  2023-01-02       B002   Smartphone  Electronics    800    100
2  2023-01-03       C003       Tablet  Electronics    500     75
Product_ID
B002    80000
B002    76000
Name: Total_Value, dtype: int64


Product_ID Product_Name
1       B002   Smartphone

### Question:

You are a data analyst for an e-commerce company. The company wants to identify its most valuable customer based on total purchase amount. You have been provided with a data dictionary containing customer order data for the first two months of 2023.

Your task is to determine which customer has spent the most money in total, and how much they have spent.  

Sample dataset:  

**data = {
    'Customer_ID': ['C001', 'C002', 'C003', 'C004', 'C005', 'C001', 'C002', 'C003', 'C004', 'C005'],
    'Order_Date': ['2023-01-15', '2023-01-16', '2023-01-17', '2023-01-18', '2023-01-19',
                   '2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05'],
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A'],
    'Quantity': [2, 1, 3, 2, 1, 1, 2, 1, 1, 3],
    'Price': [100, 150, 200, 100, 150, 200, 100, 150, 200, 100]
}**

In [ ]:

import pandas as pd

# Sample dataset
data = {
    'Customer_ID': ['C001', 'C002', 'C003', 'C004', 'C005', 'C001', 'C002', 'C003', 'C004', 'C005'],
    'Order_Date': ['2023-01-15', '2023-01-16', '2023-01-17', '2023-01-18', '2023-01-19',
                   '2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05'],
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A'],
    'Quantity': [2, 1, 3, 2, 1, 1, 2, 1, 1, 3],
    'Price': [100, 150, 200, 100, 150, 200, 100, 150, 200, 100]
}
# Load the data
df = pd.DataFrame(data)


# 1. Create total money
df['Total_Money'] = df['Quantity'] * df['Price']

# 2. Find all the unique customer ID
unique_cid = df['Customer_ID'].unique()
# print(unique_cid)

# 3. Create a variable to store the max amount and the max spending customer
max_amount = 0
most_spending_customer = None

# 4. Iterate over each customer and find the total money spend
for cid in unique_cid:
  # Extract each customer's data
  # print(f'Customer ID : {unique_cid}')
  # print(df.loc[df['Customer_ID'] == cid])
  # print('--------------------------------')

  total_amount_spent = df.loc[df['Customer_ID'] == cid, 'Total_Money'].sum()
  print(f'Customer ID: {cid} ; Money Spent: {total_amount_spent}')

  if total_amount_spent > max_amount:

    # print(f'New Maximum Found: {total_amount_spent} ; Customer ID: {cid}')
    max_amount = total_amount_spent
    most_spending_customer = cid

print(f'Customer ID : {most_spending_customer}')
print(f'Max Amount: {max_amount}')



Customer ID: C001 ; Money Spent: 400
Customer ID: C002 ; Money Spent: 350
Customer ID: C003 ; Money Spent: 750
Customer ID: C004 ; Money Spent: 400
Customer ID: C005 ; Money Spent: 450
Customer ID : C003
Max Amount: 750


In [ ]:
import numpy as np
df['Total_Price']= df['Quantity'] * df['Price']
df.set_index('Customer_ID', inplace= True)
a= []
b= []
for i in df.index.unique():
  a.append(np.sum(df.loc[i,'Total_Price']))
  b.append(i)
print(b[np.argmax(np.array(a))], np.max(np.array(a)))

C003 750


### Question:

You are an inventory manager for a retail company. The company wants to identify which product category has the highest percentage of inventory sold during March 2023. You have been provided with a data dictionary containing inventory data for the beginning and end of March 2023.

Your task is to determine:
1. Which product category has the highest percentage of inventory sold?
2. What is the percentage of inventory sold for that category?  


Sample dataset:  

**data = {
    'Product_ID': ['P001', 'P002', 'P003', 'P004', 'P005', 'P001', 'P002', 'P003', 'P004', 'P005'],
    'Date': ['2023-03-01', '2023-03-01', '2023-03-01', '2023-03-01', '2023-03-01',
             '2023-03-31', '2023-03-31', '2023-03-31', '2023-03-31', '2023-03-31'],
    'Category': ['Electronics', 'Clothing', 'Home', 'Electronics', 'Clothing',
                 'Electronics', 'Clothing', 'Home', 'Electronics', 'Clothing'],
    'Initial_Stock': [100, 200, 150, 80, 120, 70, 180, 130, 60, 100],
    'Units_Sold': [30, 20, 20, 20, 20, 40, 30, 30, 30, 30]
}**

In [ ]:

import pandas as pd

# Sample dataset
data = {
    'Product_ID': ['P001', 'P002', 'P003', 'P004', 'P005', 'P001', 'P002', 'P003', 'P004', 'P005'],
    'Date': ['2023-03-01', '2023-03-01', '2023-03-01', '2023-03-01', '2023-03-01',
             '2023-03-31', '2023-03-31', '2023-03-31', '2023-03-31', '2023-03-31'],
    'Category': ['Electronics', 'Clothing', 'Home', 'Electronics', 'Clothing',
                 'Electronics', 'Clothing', 'Home', 'Electronics', 'Clothing'],
    'Initial_Stock': [100, 200, 150, 80, 120, 70, 180, 130, 60, 100],
    'Units_Sold': [30, 20, 20, 20, 20, 40, 30, 30, 30, 30]
}
# Load the data
df = pd.DataFrame(data)
# print(df.head())

# df['Remaining_Stock'] = df['Initial_Stock'] - df['Units_Sold'] # How much stock is left

# Unique Categories
unique_categories = df['Category'].unique()

# Variable to store top category and top percentage
top_category = None
top_percentage = 0

# Iterate over each category
for cat in unique_categories:
  category_data = df.loc[df['Category'] == cat]

  # print(f'Category : {cat}')
  # print(category_data.head())
  # print('=========================================')

  percentage_sold = category_data['Units_Sold'].sum() / category_data['Initial_Stock'].sum() * 100

  # Find the maximum value
  if percentage_sold > top_percentage:
    top_percentage = percentage_sold
    top_category = cat

print(f'Product category with the highest percentage of inventory sold : {top_category}')
print(f'Highest percentage of inventory sold : {top_percentage}')

Product category with the highest percentage of inventory sold : Electronics
Highest percentage of inventory sold : 38.70967741935484


In [ ]:
# Please explain:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])

print(x)
print(v)
print((x / v[:,None])[1][1])

[[200 200 200]
 [300 300 300]
 [400 400 400]]
[200 300 400]
1.0


In [ ]:
print(v[:,None]) # Reshape operation from 1 D to 2 D

[[200]
 [300]
 [400]]


In [ ]:
print((x / v[:,None])) # Dividing each element of the row using reshaped array

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
v[ :, None]

array([[200],
       [300],
       [400]])

In [ ]:
# Q2:Please explain:
data = np.random.randint(100, size= (4,3))
a= np.vsplit(data, 4)[-1:]
print(f'a= {a}')
print(f'a.shape= {np.array(a).shape}', end='\n\n')

b= np.vsplit(data, 4)[:-1]
print(f'b= {b}')
print(f'b.shape= {np.array(b).shape}', end='\n\n')
print(f'Cyclic_shift= {a + b}', end='\n\n')
print(f'result= {np.concatenate(a + b)}')
print(f'result= {np.concatenate(a + b).shape}')

a= [array([[87, 87, 73]])]
a.shape= (1, 1, 3)

b= [array([[96, 53, 17]]), array([[ 0, 26, 38]]), array([[66, 96, 23]])]
b.shape= (3, 1, 3)

Cyclic_shift= [array([[87, 87, 73]]), array([[96, 53, 17]]), array([[ 0, 26, 38]]), array([[66, 96, 23]])]

result= [[87 87 73]
 [96 53 17]
 [ 0 26 38]
 [66 96 23]]
result= (4, 3)


In [ ]:
a= np.vsplit(data, 4)[-1:]
b= np.vsplit(data, 4)[:-1]

In [ ]:
print(a) # A list of array
print(b)

[array([[87, 87, 73]])]
[array([[96, 53, 17]]), array([[ 0, 26, 38]]), array([[66, 96, 23]])]


In [ ]:
print(type(a))

<class 'list'>


In [ ]:
np.array(a + b)

array([[[87, 87, 73]],

       [[96, 53, 17]],

       [[ 0, 26, 38]],

       [[66, 96, 23]]])

In [ ]:
a + b

[array([[87, 87, 73]]),
 array([[96, 53, 17]]),
 array([[ 0, 26, 38]]),
 array([[66, 96, 23]])]

In [ ]:
# what is the error here in last code ?
# Sample dataset
data = {
    'Customer_ID': ['C001', 'C002', 'C003', 'C004', 'C005', 'C001', 'C002', 'C003', 'C004', 'C005'],
    'Order_Date': ['2023-01-15', '2023-01-16', '2023-01-17', '2023-01-18', '2023-01-19',
                   '2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05'],
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A'],
    'Quantity': [2, 1, 3, 2, 1, 1, 2, 1, 1, 3],
    'Price': [100, 150, 200, 100, 150, 200, 100, 150, 200, 100]
}
# Load the data
df = pd.DataFrame(data)
df['totalspent'] = df['Quantity'] * df['Price']

df2=df.groupby('Customer_ID')['totalspent'].sum().sort_values(ascending=False).to_frame()
df2[df2['totalspent']==df.groupby('Customer_ID')['totalspent'].sum().sort_values(ascending=False).max()]


totalspent
Customer_ID            
C003                750

In [ ]:
df.groupby('Customer_ID')['totalspent'].sum().sort_values(ascending=False).to_frame()

Index(['totalspent'], dtype='object')